export default {
  // application actions
  LOADING: "LOADING",
  LOADED: "LOADED",

  // auth actions
  LOGGED_IN: "LOGGED_IN",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTERED: "REGISTERED",
  REGISTER_FAILED: "REGISTER_FAILED",
  USER_LOADED: "USER_LOADED",
  USER_LOAD_FAILED: "USER_LOAD_FAILED",
  LOGGED_OUT: "LOGGED_OUT",

  // inbox actions
  EMPTY_INBOX: "EMPTY_INBOX",
  INBOX_LOADED: "INBOX_LOADED",
  INBOX_LOAD_FAILED: "INBOX_LOAD_FAILED",
  MESSAGE_READ: "MESSAGE_READ",
  MESSAGE_READ_FAILED: "MESSAGE_READ_FAILED",
  MESSAGE_LOADED: "MESSAGE_LOADED",
  MESSAGE_LOAD_FAILED: "MESSAGE_LOAD_FAILED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_SEND_FAILED: "MESSAGE_SEND_FAILED",

  // employee actions
  EMPLOYEE_LOADED: "EMPLOYEE_LOADED",
  EMPLOYEE_LOAD_FAILED: "EMPLOYEE_LOAD_FAILED",
};
